name: 'shipit'
description: 'GitHub Action for reading PR labels to determine the environment'
author: 'Dariusz Czajkowski <dare.czajkowski@gmail.com>'
runs:
  using: 'node12'
  main: 'dist/index.js'
