name: 'Deploys the app'

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    name: 'Deploys the app'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        aws-token: 'aws-test-token'
        bucket-name: 'bucket-test-name'
